//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldServiceOrganization.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WorldServiceOrganizationEntities : DbContext
    {
        public WorldServiceOrganizationEntities()
            : base("name=WorldServiceOrganizationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblAccessLevel> tblAccessLevels { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblEye> tblEyes { get; set; }
        public virtual DbSet<tblOccupation> tblOccupations { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProductType> tblProductTypes { get; set; }
        public virtual DbSet<tblStatus> tblStatus { get; set; }
        public virtual DbSet<tblSex> tblSex { get; set; }
        public virtual DbSet<tblProductPackage> tblProductPackages { get; set; }
        public virtual DbSet<tblProductPackageProduct> tblProductPackageProducts { get; set; }
        public virtual DbSet<tblAddress> tblAddresses { get; set; }
        public virtual DbSet<tblDocumentImg> tblDocumentImgs { get; set; }
        public virtual DbSet<SearchField> SearchFields { get; set; }
        public virtual DbSet<tblChild> tblChilds { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblTransaction> tblTransactions { get; set; }
        public virtual DbSet<tblMRZTranslation> tblMRZTranslations { get; set; }
        public virtual DbSet<tblFontStyle> tblFontStyles { get; set; }
        public virtual DbSet<tblPerson> tblPersons { get; set; }
        public virtual DbSet<tblPassportLabelSetting> tblPassportLabelSettings { get; set; }
    
        public virtual ObjectResult<ProductUnionPackage_Result> ProductUnionPackage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductUnionPackage_Result>("ProductUnionPackage");
        }
    
        public virtual ObjectResult<CustomSearchLeftJoin_Result> CustomSearchLeftJoin(string fieldtoSearch, string searchValue)
        {
            var fieldtoSearchParameter = fieldtoSearch != null ?
                new ObjectParameter("FieldtoSearch", fieldtoSearch) :
                new ObjectParameter("FieldtoSearch", typeof(string));
    
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("SearchValue", searchValue) :
                new ObjectParameter("SearchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomSearchLeftJoin_Result>("CustomSearchLeftJoin", fieldtoSearchParameter, searchValueParameter);
        }
    
        public virtual ObjectResult<TransactionSummaryList_Result2> TransactionSummaryList(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("SearchValue", searchValue) :
                new ObjectParameter("SearchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TransactionSummaryList_Result2>("TransactionSummaryList", searchValueParameter);
        }
    
        public virtual ObjectResult<PersonExportData_Result> PersonExportData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PersonExportData_Result>("PersonExportData");
        }
    
        public virtual ObjectResult<CountrySummaryList_Result2> CountrySummaryList(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("SearchValue", searchValue) :
                new ObjectParameter("SearchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CountrySummaryList_Result2>("CountrySummaryList", searchValueParameter);
        }
    
        public virtual ObjectResult<PersonList_Result> PersonList(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("SearchValue", searchValue) :
                new ObjectParameter("SearchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PersonList_Result>("PersonList", searchValueParameter);
        }
    
        public virtual ObjectResult<sp_PersonDataTableData_Result> sp_PersonDataTableData(Nullable<int> pageIndex, Nullable<int> pageSize, string filter, Nullable<int> recordType)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("Filter", filter) :
                new ObjectParameter("Filter", typeof(string));
    
            var recordTypeParameter = recordType.HasValue ?
                new ObjectParameter("RecordType", recordType) :
                new ObjectParameter("RecordType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PersonDataTableData_Result>("sp_PersonDataTableData", pageIndexParameter, pageSizeParameter, filterParameter, recordTypeParameter);
        }
    }
}
