//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldServiceOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public int AddressIDNumber { get; set; }
        public string CareOf { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> AddressVector { get; set; }
        public Nullable<bool> Label { get; set; }
        public Nullable<int> SexId { get; set; }
        public Nullable<int> PersonIDNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblSex tblSex { get; set; }
        public virtual tblPerson tblPerson { get; set; }
    }
}
