//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldServiceOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChild
    {
        public int ChildId { get; set; }
        public string Name { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> SexId { get; set; }
        public Nullable<int> PersonIDNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> BirthDay { get; set; }
        public Nullable<int> BirthMonth { get; set; }
        public Nullable<int> BirthYear { get; set; }
    
        public virtual tblPerson tblPerson { get; set; }
        public virtual tblSex tblSex { get; set; }
    }
}
