//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldServiceOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPassportLabelSetting
    {
        public int PassportLabelSettingId { get; set; }
        public string Name { get; set; }
        public Nullable<int> XPassportNumber { get; set; }
        public Nullable<int> YPassportNumber { get; set; }
        public Nullable<int> XName { get; set; }
        public Nullable<int> YName { get; set; }
        public Nullable<int> XGivenName { get; set; }
        public Nullable<int> YGivenName { get; set; }
        public Nullable<int> XPlaceofBirth { get; set; }
        public Nullable<int> YPlaceofBirth { get; set; }
        public Nullable<int> XDateofBirth { get; set; }
        public Nullable<int> YDateofBirth { get; set; }
        public Nullable<int> XGender { get; set; }
        public Nullable<int> YGender { get; set; }
        public Nullable<int> XDateofIssue { get; set; }
        public Nullable<int> YDateofIssue { get; set; }
        public Nullable<int> XDateofExpiry { get; set; }
        public Nullable<int> YDateofExpiry { get; set; }
        public Nullable<int> XPhoto { get; set; }
        public Nullable<int> YPhoto { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
